name: Publish drivesecrets
run-name: ${{ github.actor }} is publishing drivesecrets to pypi
on:
  push:
    branches:
      - 'main'
      - 'releases/**'

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.16
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
